const guaranteeBase = () => ({
  id: '',
  tipo: '',
  penhor: {
    tipo: 'penhor',
    tipo_penhor: '',
    produto: '',
    grauPenhor: '',
    quantidade: '',
    safra: '',
    mesmoLocalLavoura: '',
    nomeFazenda: '',
    areaPlantio: '',
    uf: '',
    cidade: '',
    numeroMatricula: '',
    ufComarcaRegistro: '',
    cidadeComarcaRegistro: '',
    areaPropriaOuTerceiros: 'propria',
    file: [],
    obs: '',
  },
  hipoteca: {
    tipo: 'hipoteca',
    tipo_hipoteca: '',
    descricaoImovel: '',
    grauHipoteca: '',
    numeroMatricula: '',
    ufComarcaRegistro: '',
    cidadeComarcaRegistro: '',
    file: [],
    obs: '',
  },
  avalista: {
    tipo: 'pf',
    tipo_avalista: '',
    tipoAssinatura: '',
    pessoaFisica: {
      cpf: '',
      razaoSocial: '',
      rg: '',
      email: '',
      ocupacao: '',
      nacionalidade: '',
      cep: '',
      endereco: '',
      uf: '',
      cidade: '',
      estadoCivil: '',
      file: [],
      obs: '',
      conjuge: {
        nome: '',
        cpf: '',
        email: '',
        rg: '',
      },
    },
    pessoaJuridica: {
      cnpj: '',
      razaoSocial: '',
      email: '',
      cep: '',
      endereco: '',
      uf: '',
      cidade: '',
      file: [],
      obs: '',
    },
  },
});

export {
  // eslint-disable-next-line import/prefer-default-export
  guaranteeBase,
};
