export default {
  guarantee_list: [
    {
      id: '',
      titulo: '',
      tipo: 'penhor',
      penhor: {
        tipo: 'penhor',
        tipoPenhor: '',
        produto: '',
        grauPenhor: '',
        quantidade: '',
        safra: '',
        mesmoLocalLavoura: true,
        nomeFazenda: '',
        areaPlantio: '',
        uf: '',
        cidade: '',
        numeroMatricula: '',
        ufComarcaRegistro: '',
        cidadeComarcaRegistro: '',
        areaPropriaOuTerceiros: 'propria',
        file: [],
        obs: '',
      },
      hipoteca: {
        tipo: 'mortgage',
        tipoHipoteca: '',
        descricaoImovel: '',
        grauHipoteca: '',
        numeroMatricula: '',
        ufComarcaRegistro: '',
        cidadeComarcaRegistro: '',
        file: [],
        obs: '',
      },
      avalista: {
        tipo: 'pf',
        pessoaFisica: {
          cpf: '',
          razaoSocial: '',
          rg: '',
          email: '',
          ocupacao: '',
          nacionalidade: '',
          cep: '',
          endereco: '',
          uf: '',
          cidade: '',
          estadoCivil: '',
          file: [],
          obs: '',
          conjuge: {
            nome: '',
            cpf: '',
            email: '',
            rg: '',
          },
        },
        pessoaJuridica: {
          cnpj: '',
          razaoSocial: '',
          email: '',
          cep: '',
          endereco: '',
          uf: '',
          cidade: '',
          file: [],
          obs: '',
        },
      },
    },
  ],
  guarantee: {
    id: '',
    titulo: '',
    tipo: 'penhor',
    penhor: {
      tipo: 'penhor',
      tipoPenhor: '',
      produto: '',
      grauPenhor: '',
      quantidade: 0,
      safra: '',
      mesmoLocalLavoura: true,
      nomeFazenda: '',
      areaPlantio: 0,
      uf: '',
      cidade: '',
      numeroMatricula: '',
      ufComarcaRegistro: '',
      cidadeComarcaRegistro: '',
      areaPropriaOuTerceiros: 'propria',
      file: [],
      obs: '',
    },
    hipoteca: {
      tipo: 'hipoteca',
      tipo_hipoteca: '',
      descricaoImovel: '',
      grauHipoteca: '',
      numeroMatricula: '',
      ufComarcaRegistro: '',
      cidadeComarcaRegistro: '',
      file: [],
      obs: '',
    },
    avalista: {
      tipo: 'pf',
      tipoAssinatura: '',
      pessoaFisica: {
        cpf: '',
        razaoSocial: '',
        rg: '',
        email: '',
        ocupacao: '',
        nacionalidade: '',
        cep: '',
        endereco: '',
        uf: '',
        cidade: '',
        estadoCivil: '',
        file: [],
        obs: '',
        conjuge: {
          nome: '',
          cpf: '',
          email: '',
          rg: '',
        },
      },
      pessoaJuridica: {
        cnpj: '',
        razaoSocial: '',
        email: '',
        cep: '',
        endereco: '',
        uf: '',
        cidade: '',
        file: [],
        obs: '',
      },
    },
  },
};
