const title = (state) => state.title;
const titleBase = () => ({
  tituloId: '',
  clienteId: '',
  cpr: '',
  tipoCpr: '',
  status: 1,
  tipo: '',
  produto: '',
  lavoura: '',
  quantidade: '',
  quantidadeSacas: '',
  expiracao: '',
  proprioEmitente: '',
  emitentes: [],
  produtividade: '',
  areaProducao: '',
  nomeFazenda: '',
  uf: '',
  municipio: '',
  ufRegistro: '',
  numeroMatricula: '',
  municipioRegistro: '',
  areaReservaLegal: '',
  areaReservaTotal: '',
  latitude: '',
  longitude: '',
  files: [],
  estadoCivil: '',
  ocupacao: '',
  email: '',
  rg: '',
  nome: '',
  cpf: '',
  tipoArea: '',
  proprietarios: [],
  localEntrega: '',
  cepEntrega: '',
  enderecoEntrega: '',
  ufEntrega: '',
  cidadeEntrega: '',
  periodoEntrega: '',
  depositarioEmitente: '',
  tipoPessoaDepositario: '',
  created: '',
  depositario: {
    // tipoPessoaDepositario: '',
    uf: '',
    cidade: '',
    cep: '',
    endereco: '',
    nacionalidade: '',
    estadoCivil: '',
    ocupacao: '',
    email: '',
    rg: '',
    nome: '',
    cpf: '',
    obs: '',
    cnpj: '',
    razao_social: '',
    tipoAssinatura: 'eletronic',
  },
  currentStep: 1,
});
const pfRequiredFields = () => [
  'uf',
  'municipio',
  'cep',
  'endereco',
  'nacionalidade',
  'estadoCivil',
  'ocupacao',
  'email',
  'rg',
  'nome',
  'cpf',
  'obs',
];

const pjRequiredFields = () => [
  'cnpj',
  'razaoSocial',
  'email',
  'cep',
  'endereco',
  'uf',
  'municipio',
];
export {
  // eslint-disable-next-line import/prefer-default-export
  title,
  titleBase,
  pfRequiredFields,
  pjRequiredFields,
};
